import React from 'react';
import { type InfographicData } from '../services/ai';
import { BookOpen, Zap, Clock, Lightbulb, Info } from 'lucide-react';

interface InfographicProps {
    data: InfographicData;
}

export const Infographic: React.FC<InfographicProps> = ({ data }) => {

    const getIcon = (type: string) => {
        switch (type) {
            case 'process': return <Zap size={24} />;
            case 'history': return <Clock size={24} />;
            case 'fact': return <Info size={24} />;
            default: return <BookOpen size={24} />;
        }
    };

    return (
        <div className="infographic-container" style={{
            background: '#f2f0ea',
            color: '#1a1a1a',
            width: '100%',
            maxWidth: '800px',
            margin: '0 auto',
            border: '2px solid #1a1a1a',
            position: 'relative',
            overflow: 'hidden'
        }}>
            {/* Header Section */}
            <header style={{
                borderBottom: '2px solid #1a1a1a',
                padding: '3rem',
                background: '#1a1a1a',
                color: '#f2f0ea'
            }}>
                <div style={{
                    textTransform: 'uppercase',
                    letterSpacing: '0.2em',
                    fontSize: '0.8rem',
                    marginBottom: '1rem',
                    opacity: 0.8
                }}>
                    Study Material / Generated Asset
                </div>
                <h1 style={{
                    fontSize: '3.5rem',
                    lineHeight: 1,
                    fontFamily: 'Manrope, sans-serif',
                    fontWeight: 800,
                    marginBottom: '1.5rem'
                }}>
                    {data.title}
                </h1>
                <p style={{
                    fontSize: '1.25rem',
                    lineHeight: 1.6,
                    fontFamily: 'Playfair Display, serif',
                    fontStyle: 'italic',
                    opacity: 0.9,
                    borderLeft: '2px solid #ff3333',
                    paddingLeft: '1.5rem'
                }}>
                    {data.summary}
                </p>
            </header>

            {/* Grid Body */}
            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr' }}>
                {data.keyPoints.map((point, index) => (
                    <div key={index} style={{
                        padding: '2.5rem',
                        borderRight: index % 2 === 0 ? '2px solid #1a1a1a' : 'none',
                        borderBottom: index < 2 ? '2px solid #1a1a1a' : 'none',
                        display: 'flex',
                        flexDirection: 'column',
                        gap: '1rem'
                    }}>
                        <div style={{
                            width: '50px',
                            height: '50px',
                            border: '1px solid #1a1a1a',
                            display: 'flex',
                            alignItems: 'center',
                            justifyContent: 'center',
                            borderRadius: '50%',
                            background: 'white',
                            marginBottom: '0.5rem'
                        }}>
                            {getIcon(point.iconType)}
                        </div>
                        <h3 style={{ fontSize: '1.25rem', fontWeight: 700, textTransform: 'uppercase' }}>{point.title}</h3>
                        <p style={{ fontSize: '1rem', color: '#5a5a5a', lineHeight: 1.5 }}>{point.description}</p>
                    </div>
                ))}
            </div>

            {/* Footer / Fun Fact */}
            <div style={{
                borderTop: '2px solid #1a1a1a',
                padding: '2rem',
                background: '#ff3333',
                color: 'white',
                display: 'flex',
                alignItems: 'center',
                gap: '1.5rem'
            }}>
                <Lightbulb size={32} strokeWidth={2.5} />
                <div>
                    <div style={{ fontWeight: 800, textTransform: 'uppercase', fontSize: '0.9rem', marginBottom: '0.25rem', opacity: 0.9 }}>Did You Know?</div>
                    <p style={{ fontSize: '1.1rem', fontWeight: 500 }}>{data.funFact}</p>
                </div>
            </div>

            {/* Watermark */}
            <div style={{
                position: 'absolute',
                top: '1rem',
                right: '1rem',
                fontSize: '0.7rem',
                textTransform: 'uppercase',
                opacity: 0.5,
                color: '#f2f0ea'
            }}>
                Generated by FlashGen AI
            </div>
        </div>
    );
};
